### ISSUE TITLE
Dropdown is not working on local machine running on http

### ISSUE THREAD

**Issue by renil** [OfficeDev/office-ui-fabric-js#144]
It looks like the dropdown is trying to load MirosoftAjax.js using http and not able to load properly. This is affecting the functionality of Dropdown.

**Comment by renil** [comment]
My bad. It looks like the error came from office.js and not from fabric js. It is trying to contact https://ajax.aspnetcdn.com/ajax/3.5/MicrosoftAjax.js it looks like.

I have used the version of fabric js from bower. 
- The Dropdown is not displaying any records. Before initializing the dropdown, it has records.
- Also the dropdown is not getting opened when I increase the width of the add-in.
It may be related to the version I am using. I see a mismatch between the documentation online and the version in bower. The version in bower is using jQuery plugin model.

```
"office-ui-fabric-core": "office-ui-fabric#^4.1.0",
"office-ui-fabric": "office-ui-fabric-js#^2.6.1"
```

**Comment by ericthompson** [comment]
We're thinking this might have to do with some funkiness we're experiencing with Bower - @Jahnp.

**Comment by Jahnp** [comment]
Thanks--I'll take a look at this.

**Comment by Jahnp** [comment]
Alright, fixed the Bower issue.

The problem was that all of the old releases from office-ui-fabric from before the core/JS split carried over when we forked the project, including their tags. So Bower was actually picking up the old releases, rather than the newer JS releases. This is why you were getting the older version installed :)

I've deleted all of the old releases now and verified via `bower install office-ui-fabric-js` that the *actual* new releases are being picked up. You should be able to do the same. Please give the new versions of the Fabric JS components a try, and let us know if you're still experience weirdness. I'll close this issue in the meantime since the Bower issue has been resolved. Thanks again for reporting the issue, @renil!
