### ISSUE TITLE
Components are not initialized consistently

### ISSUE THREAD

**Issue by renil** [OfficeDev/office-ui-fabric-js#146]
It looks like the components are initialized with different approaches. For instance, spinner is initialized with:

```
var element = document.querySelector('.ms-Spinner');
var spinner = new fabric["Spinner"](element);
```
while Dropdown is initialized with:
```
$('.ms-Dropdown').Dropdown()
```

Can we make it consistent? Are there non-jQuery version of components available?

**Comment by Jahnp** [comment]
Hi @renil, which version are you using? In the 1.0 release of Office UI Fabric JS, all of the components' JavaScript was rewritten using TypeScript; this should have normalized the initialization process to mirror the example you used for the Spinner.

**Comment by renil** [comment]
I have used the one from bower. I will check the version once again.

**Comment by renil** [comment]
Where do I get the latest version of fabric js and the typescript definition files?

**Comment by ericthompson** [comment]
To the question about the JS files not having a version number, [we actually just merged in a PR that supplies these so that future versions can be more easily differentiated](https://github.com/OfficeDev/office-ui-fabric-js/pull/131).

We currently don't have Typescript definition files, but we are [tracking a request for this](https://trello.com/c/S7rgV8Ip/28-typescript-definitions-for-components).

You can get the latest version of Fabric JS by downloading the release and including it in your project or using [NPM](https://www.npmjs.com/package/office-ui-fabric-js) / Bower:
![image](https://cloud.githubusercontent.com/assets/1420854/19202545/a589c15e-8c87-11e6-893d-9dfd12ed2df0.png)

We'll keep tracking what's going on with Bower via [the other issue](https://github.com/OfficeDev/office-ui-fabric-js/issues/122).
