### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by Levitas** [OfficeDev/office-ui-fabric-js#155]
Hello there,

a bunch of icons shown at http://dev.office.com/fabric#/styles/icons are not available in this package.
Im using the nuget version.

for example: .ms-Icon--Ticket

Am i doing sth wrong or are they missing?

**Comment by ericthompson** [comment]
Hi @Levitas - the icons you're seeing on the site are a part of the *new* iconography that is a part of the latest releases of Fabric JS, Fabric Core, and Fabric React.

If you're using the [OfficeUIFabric](http://www.nuget.org/packages/OfficeUIFabric/) package, then you're referencing the **v2.6.1** of Fabric. In order to see the icons available, please use the following the instructions:
1. Clone the the [Core project](https://github.com/OfficeDev/office-ui-fabric-core)
2. Checkout the branch for the 2.6.1 release: `git checkout release/2.6.1` from the command line
3. Navigate to the folder that contains the gulpfile.js file (Fabric's root)
4. `npm install`
5. `gulp watch`

Navigating to localhost:2020, you can check out this page:
![image](https://cloud.githubusercontent.com/assets/1420854/19204260/9c8963e4-8c90-11e6-8f07-9fbb401b563a.png)

If you'd like to use the icons on the [Fabric site](http://dev.office.com/fabric), we have another NuGet package - [OfficeUIFabricJS](http://www.nuget.org/packages/OfficeUIFabricJS/) - which includes the latest icons, styling, and components.

Let me know if you have questions!

**Comment by Levitas** [comment]
Actually im using exactly this nuget package. 
Version 1.1.0 @ericthompson 

Example: ms-Icon-Ticket: 
![image](https://cloud.githubusercontent.com/assets/6342317/19302567/e93dea34-9064-11e6-9532-61328bb36494.png)
This doesnt show up.
Code for Tickets:
```html
       <div class="ms-CommandButton" style="">
            <a class="ms-CommandButton-button" href="/Ticket">
                <span class="ms-CommandButton-icon ms-fontColor-themePrimary">
                    <i class="ms-Icon ms-Icon--Ticket"></i>
                </span>
                <span class="ms-CommandButton-label">Tickets</span>
            </a>
        </div>
```
Code for Dashboard:
```html
<div class="ms-CommandButton" style="">
            <a class="ms-CommandButton-button" href="/">
                <span class="ms-CommandButton-icon ms-fontColor-themePrimary">
                    <i class="ms-Icon ms-Icon--Home"></i>
                </span>
                <span class="ms-CommandButton-label">Dashboard</span>
            </a>
        </div>
```

NuGet Package Version 1.1.0: 
![image](https://cloud.githubusercontent.com/assets/6342317/19302674/62ae269a-9065-11e6-83a3-6fc42afbbe21.png)

**Comment by ericthompson** [comment]
OK - that's no good. We'll look into this and see if we can track down why it's not showing up. Is the **Ticket** icon the only one you're aware of that's missing?

**Comment by Jahnp** [comment]
So it looks like the NuGet package for 1.1.0 is actually missing a bunch of icons for some reason. Looks like the CSS was built incorrectly. I think it'll be solved by re-building and patching the NuGet file--will try to take a look at that asap. I'll follow up on this issue when that's been done.

**Comment by Levitas** [comment]
hey I just wanted to know whats the current status, i didnt found the bug by myself.
Its a pretty annoying issue when there are spaces instead of icons 👍

**Comment by Jahnp** [comment]
Sorry for the delay! I've investigated and confirmed that the package built & uploaded for the 1.1.0 release contained some anomalies--there were probably local artifacts from a prior build that snuck in. I've rebuilt the package locally to confirm this.

I've contacted NuGet support to see if I can re-upload the correct package for 1.1.0. Failing that, it might be best to wait for the next release of Fabric JS, which will likely be 1.2.0. If that's the case we'll make sure the next package is 100% correct on upload :)

**Comment by Jahnp** [comment]
Ok, I've re-uploaded the [1.1.0 release here](https://www.nuget.org/packages/OfficeUIFabricJS/1.1.0). @Levitas would you mind taking a look to see if this resolves your issue?

**Comment by Levitas** [comment]
Thank you :) i will check it tomorrow and give an info here.

**Comment by Jahnp** [comment]
Great, thank you!

**Comment by Levitas** [comment]
No success.

Note: If i use it from the cdn it works just fine.

My Code
´´´html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    


    <link rel="stylesheet" href="/Content/fabric.min.css">
    <link rel="stylesheet" href="/Content/fabric.components.css">
</head>
<body>

<i class="ms-Icon ms-Icon--Ticket"></i>
<i class="ms-Icon ms-Icon--Home"></i>
    @RenderBody(

</body>
</html>

´´´

**Comment by Jahnp** [comment]
Oh, that's super annoying. Sorry for the hassle! To be clear, is it *still* not working after consuming the [new, updated NuGet package](https://www.nuget.org/packages/OfficeUIFabricJS/1.1.0)? I just manually downloaded the package from here and opened Content/fabric.min.css, and I'm seeing both the `ms-Icon--Ticket`:
![image](https://cloud.githubusercontent.com/assets/307118/19774360/a7ff5364-9c21-11e6-98ad-142c91f249ab.png)

As well as code for all of the other icon definitions (note the #of matches for `ms-Icon--`):
![image](https://cloud.githubusercontent.com/assets/307118/19774379/ba334fa4-9c21-11e6-8c7d-5f07228fdf46.png)

You can tell because this is the CSS from Fabric 4.0:
![image](https://cloud.githubusercontent.com/assets/307118/19774419/d6c3c982-9c21-11e6-9f18-683403706410.png)

Could you provide more detail around which package you are consuming, and ideally the version # of the fabric.min.css file that's failing for you?

**Comment by Levitas** [comment]
I recreated a new visual studio project and added the nuget package.
Do I have to do more than that?

**Comment by Jahnp** [comment]
You shouldn't have to do anything else, no.  I just created an Excel add-in in VS 2015 myself and installed the new package via the NuGet Package Manager, and the updated content is showing up for me:

![image](https://cloud.githubusercontent.com/assets/307118/19938103/01de6e60-a0e1-11e6-82f7-b89534eaf594.png)


It's possible that your [local NuGet cache](https://docs.nuget.org/ndocs/consume-packages/managing-the-nuget-cache) is holding onto the old version--perhaps you need to clear it to view the latest from nuget.org. Could you try that and let me know if you're still not seeing the icons?

**Comment by Levitas** [comment]
I removed the cache, but no success.
The CSS file has the creation date from 26th, october, so it should be the newest one.

My Code:
```html
<a href="/Customer" class="bigbutton">
                <i class="icon ms-Icon ms-Icon--ContactInfo"></i>
                <p class="description">Kundenübersicht</p>
            </a>
<a href="/Ticket" class="bigbutton">
                <i class="icon ms-Icon ms-Icon--Ticket"></i>
                <p class="description">Ticketübersicht</p>
            </a>
            <a href="/Company" class="bigbutton">
                <i class="icon ms-Icon ms-Icon--Suitcase"></i>
                <p class="description">Firmenübersicht</p>
            </a>
```

When using the cdn files, it works just fine.

The first works and the second doesnt.

**Comment by ericthompson** [comment]
Can you confirm that "ContactInfo" works, but "Ticket" doesn't?

**Comment by Levitas** [comment]
Yes.

![image](https://cloud.githubusercontent.com/assets/6342317/20485156/96be5630-affa-11e6-9276-6fff3a184a2e.png)
´´´html
<b>Ticket:</b> <i class="ms-Icon ms-Icon--Ticket"></i><br />
<b>Contactinfo:</b> <i class="ms-Icon ms-Icon--ContactInfo"></i>
´´´

**Comment by Levitas** [comment]
I updated the package to version 1.2.0
this solved this issue (also deletes the sass files, but i dont need them anyway)

Thank you!
