### ISSUE TITLE
DatePicker: Selecting a Month does not work in IE11 or Edge

### ISSUE THREAD

**Issue by goof1972** [OfficeDev/office-ui-fabric-js#159]
The grid where a user selects a month from the DatePicker control doesn't work in IE11 or Edge. When I click on a month...nothing happens. The date doesn't change. (see attached picture).

![datepickererror](https://cloud.githubusercontent.com/assets/19931021/19364597/d218b02a-915c-11e6-90dd-a382c52251c7.png)

All other functions work including changing the Month by clicking on the chevrons.

What is ironic is that it works in Chrome.

Any idea how to get around this bug?

**Comment by Jahnp** [comment]
Hi @goof1972, thanks for reporting this issue. Are any console errors fired when clicking on months? We haven't seen this error before, but will definitely investigate.

**Comment by goof1972** [comment]
Hi @jahnp, thanks for looking into it.

When I click on one of the Months, nothing happens and nothing appears in the Console. I tested this on Edge and IE11 (see screenshot below)

![datepickererror](https://cloud.githubusercontent.com/assets/19931021/19394891/0d403fe0-9209-11e6-848f-aa84db4d8681.png)

The highlighted Month doesn't change either.

**Comment by Jahnp** [comment]
Gotcha--thanks for the details and quick investigation! We'll dig in and hopefully have a fix before too long.

**Comment by Giantaxe** [comment]
In Jquery.DatePicker.ts

under these 2 functions
- (line: 173) `$monthPicker.on("click", ".js-changeDate", (event) => {`
- (line: 193) `$yearPicker.on("click", ".js-changeDate", (event) => {`

changing
`let $changeDate = $(event.toElement);`
to:
`let $changeDate = $(event.target);`

seems to fix the issue, for some reason event.toElement returns undefined in IE & Edge but .target works fine. Although since its JQuery you could replace `event.target` with `this`

**Comment by Jahnp** [comment]
That's a great catch, @Giantaxe--thanks for investigating! Substituting `event.target` for `event.toElement` seems like a [pretty common](http://stackoverflow.com/questions/8600174/event-toelement-in-ie8-and-firefox) solution to this problem. Did you notice any other issues with that change? Happy to make the change here myself, otherwise we'd welcome a PR.

**Comment by Giantaxe** [comment]
Added a PR

As for issues, so far encountered none. the datepicker seems to work fine in IE, Edge, FireFox and Chrome.

**Comment by goof1972** [comment]
Just tried it now and it works in Chrome, Edge, and IE11. Thanks for the quick fix!
