### ISSUE TITLE
Styling different from react callout component 

### ISSUE THREAD

**Issue by sjkp** [OfficeDev/office-ui-fabric-js#210]
I have noticed that there styling of the component is not identical between the native js components and the react components. 

This is a problem, as you only show the react on the demo page, and users would expect that the two flavors of the components to be identical. 

I have only tested with the callout component https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/components/Callout.md 

But with the current styles sheets listed on the readme.md 

<link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/5.0.1/css/fabric.min.css">
  <link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.components.min.css">

You don't get a callout that is styled anywhere close to what you would expect (eg. borders are missing).  

It is not surprising, if you look at the react component, it scss is quite different from the native js component: 

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Callout/Callout.scss

**Comment by sjkp** [comment]
Okay I realize that it the links on the readme.md
```
<link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/5.0.1/css/fabric.min.css">
<link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-js/1.2.0/css/fabric.components.min.css"> 
```

That are just not compatible with the fabric-js components. They should be changed to
```
<link rel="stylesheet" href="https://appsforoffice.microsoft.com/fabric/2.6.1/fabric.min.css">
<link rel="stylesheet" href="https://appsforoffice.microsoft.com/fabric/2.6.1/fabric.components.min.css">
```

**Comment by ericthompson** [comment]
Hi @sjkp!

The [2.6.1.](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/ghdocs/V2GETSTARTED.md) version you're referring to is actually a previous version of Fabric that included both the Core and the JS components. The non-React components are now contained in the Fabric JS project with the icons, colors, grid, and other non-component assets being in the [Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core) project.

You can follow the instructions linked to above in order to use the 2.6.1 project, but, for the latest JS components (currently on 1.2.0), you'll want to follow the instructions in the [JS project's main README](https://github.com/OfficeDev/office-ui-fabric-js). If you use the latest JS components (as seen in the [existing md documentation](https://github.com/OfficeDev/office-ui-fabric-js/blob/master/ghdocs/COMPONENTSLIST.md)), you'll notice that the styling is much closer, although still slightly different as the two projects are not directly linked outside of using Fabric Core.

We are currently planning to work on a live documentation site for the Fabric JS components, but you can also [build the JS project locally](https://github.com/OfficeDev/office-ui-fabric-js#clone-build-and-view-the-docs) in order to see the responsive behavior of the components. Once the new site is up, we'll do work to help clarify which components are displayed where to help cut down on some of this confusion.

Let us know if you have further questions!
