### ISSUE TITLE
List control style bug?

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#238]
The list control from Fabric JS and it's counterpart in Fabric React (the Inbox variant) appear to use different styles. Is this intentional? 

The styles used in this control are too large to be used in an Office Add-in.

Thanks!

**Comment by ericthompson** [comment]
@Reezaali - thanks for filing this issue. The Fabric JS and Fabric React projects are not directly connected outside of following the Office Design Language and their dependency on Fabric Core. The List available in Fabric JS follows the same aesthetic as the Outlook Web App's Inbox list.

It sounds like this issue is actually a component request for a list that is more suitable for Add-ins (smaller?). Do you have any recommendations or examples of a list that is suitable?

**Comment by Reezaali** [comment]
@jedunn Do you have any list examples to share with Eric? Thanks!

**Comment by Linda-Editor** [comment]
Microsoft no longer supports this content and will not be responding to bugs or issues. We recommend that you use the newer version, [Office UI Fabric](https://developer.microsoft.com/fabric), with React as your front-end framework. We are closing this issue; if you still need assistance with Fabric.js, visit [Stack Overflow/office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).
