### ISSUE TITLE
Dialog Overlay

### ISSUE THREAD

**Issue by echoworxdev** [OfficeDev/office-ui-fabric-js#242]
Hi there,

The overlay with the dialog doesn't actually block the background, instead dismisses on click, which wasn't the case with Fabric 2.6.2. It is not a desired feature as I am performing some asynchronous task in the background.
Sticking to the current behavior requires me to add my own click listener to the overlay to reject the asynchronous process manually. 
kindly look into it asap.

**Comment by stijnkiers** [comment]
Hi echoworxdev,
I think this behaviour is intended. If you don't want the dialog to be dismissed on overlay click there is the blocking variant of the dialog.

That said, I have the issue that the overlay does not block the background and only closes the dialog when I click an empty spot on the page. If I click a (command)button, the button's action is executed instead of the dialog being closed.
On the sample page I don't have this issue, so what am I doing wrong?

**Comment by Linda-Editor** [comment]
Microsoft no longer supports this content and will not be responding to bugs or issues. We recommend that you use the newer version, [Office UI Fabric](https://developer.microsoft.com/fabric), with React as your front-end framework. We are closing this issue; if you still need assistance with Fabric.js, visit [Stack Overflow/office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).
