### ISSUE TITLE
CommandBar: Event handlers lost when moved into overflow

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-js#26]
_From @MJZawacki on June 24, 2016 22:19_

I'm seeing issues in an Office add-in on Mac where the event is not fired when the command is hidden in the overflow menu.

What is the intended way to link up click events so that they work while inside the overflow menu? The element id's from the original ms-CommandBarItem's are not persisted by createMenuItem so it's unclear to me how you intended to hook up the event. 

_Copied from original issue: OfficeDev/office-ui-fabric-core#691_

**Comment by mikewheaton** [comment]
This bug repros in Fabric 3.0 as well. If you set an onClick handler on a CommandButton, that handler is lost when the button is moved into the overflow menu.

**Comment by mikewheaton** [comment]
_From @schott12521 on July 6, 2016 14:11_

I was able to add a link for the overflow buttons using this snippet in the javascript function for createMenuItem:

```javascript
var item = '<li class="ms-ContextualMenu-item"><a class="ms-ContextualMenu-link" href="' + linkToButton + '">';
item += /* Button link action */
item += '</a></li>';
```

However, I'm running into some more problems with the commandBar and it's overflow now. If I click outside the area that turns the mouse into a pointer, I will be correctly taken to the link using my method above. However, if I click inside the actual ellipsis area that turns my mouse into a pointer, the overflow will pop open, but no action will be taken.

Additionally, if I click outside the pointer area, I can click multiple command bar overflows and it will not cause the other overflows to hide.

**Comment by seriewe** [comment]
Hi,
I was trying to copy the onclick events to the newCItem, but the events allays trigger on the Button not on the new a tag and I get an Error. 

Because my Button onclick always has an location.href="..." I used the following workaround, this workaround is not really god but works for me:

`var btn = <HTMLButtonElement>this.overflowCommands[i].item.querySelector(".ms-CommandButton-button");
        if(btn.getAttribute("onclick")){
          var uri = btn.getAttribute("onclick").split("href=");
          newClink.setAttribute("href", uri[1].replace("'",""));
        }                `

This would'n work if somebody use other onclick events like a alert. Has somebidy an idea how I can copy the btn.onclick method and bind to the new Link Element, so the function triggers on the Link?

Best regards.

**Comment by Linda-Editor** [comment]
Microsoft no longer supports this content and will not be responding to bugs or issues. We recommend that you use the newer version, [Office UI Fabric](https://developer.microsoft.com/fabric), with React as your front-end framework. We are closing this issue; if you still need assistance with Fabric.js, visit [Stack Overflow/office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).
