### ISSUE TITLE
Bower has old package

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-js#260]
It looks like `bower i office-ui-fabric-js` installs 2.6.1 instead of 1.2.0 or 1.3.0.  
NPM and Nuget are both at 1.3

**Comment by Jahnp** [comment]
Thanks for reporting this, @manndave, and sorry for the hassle. 

We've definitely [fixed this issue before](https://github.com/OfficeDev/office-ui-fabric-js/issues/144), but it keeps cropping up; I'm guessing that someone with an old branch is pushing old tags from their local repo. We'll look into fixing this as a pattern moving forward.

**Comment by tylerjwatson** [comment]
Hi guys,

Any movement on this issue?  As we use grunt-usemin in our pipeline it's significantly easier to integrate the bower package in our build process rather than the npm one.  Alternatively, is there a specific workaround (such as checking out 1.3.0 explicitly with bower maybe?) that would get around the problem for now?

I'd  love to use the new components as they differ slightly.

Cheers,
T.

**Comment by Jahnp** [comment]
Sorry for the hassle, @tylerjwatson. I've just cleared out all the old releases, so things should work as expected again. We're still trying to identify exactly why these tags keep getting pushed--we probably just need to hassle the team to stop using old repos :)

That said, yeah, locking to a specific version in `bower.json` is a much safer route and is considered best-practice for managing dependencies--it should let you side-step this issue altogether.

**Comment by tylerjwatson** [comment]
Thanks @Jahnp for your prompt feedback. I ended up side-stepping issue by installing the `release/1.3.0` tag.

For everybody else:  to install v1.3.0 via bower, use the following command:

```bash
$ bower i https://github.com/OfficeDev/office-ui-fabric-js.git#release/1.3.0 --save
```

We lose the semver updating semantics but I'm happy to stay locked if it gives us an up-to-date package.

Cheers!

**Comment by Jahnp** [comment]
Awesome! Glad that helped @tylerjwatson, and thanks for the suggestion for all others. 

And, again, apologies for the inconvenience--we realize this is frustrating and unintuitive, and impacts other downstream projects negatively (e.g. ngOfficeUIFabric). 

So you know, I'm pushing hard on our side to clean up our local clones to make sure this doesn't happen again; unfortunately it doesn't seem that GitHub has a way of "locking" releases, or preventing the creation of releases by merely pushing tags. Since this repo was created as a clone of the original Fabric repo--old tags/releases and all!--this will continue to be an issue until all main contributors have effectively started fresh. I'll consider this issue "open" until we can verify things have been cleaned up.

**Comment by bpatra** [comment]
After cleaning bower cache `bower cache --clean` I still have the problem

**Comment by Jahnp** [comment]
It looks like it regressed again. Sorry for the hassle... I'll follow up on our side.

**Comment by Jahnp** [comment]
Ok, cleaned up the releases again. Please let me know if it regresses for you again.

Also, just to confirm, in what scenario(s) are you encountering this? In most cases where this would be an issue, I would think that specifying a specific version of the project would be ideal rather than the generic, unversioned one. I realize this shouldn't be a problem in the first place--I'll see about locking down tag pushing for the repo--but if you, say, specify a particular version in your `bower.json`, it should help you avoid this problem.

**Comment by Linda-Editor** [comment]
Microsoft no longer supports this content and will not be responding to bugs or issues. We recommend that you use the newer version, [Office UI Fabric](https://developer.microsoft.com/fabric), with React as your front-end framework. We are closing this issue; if you still need assistance with Fabric.js, visit [Stack Overflow/office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).
