### ISSUE TITLE
Question: Typings Files?

### ISSUE THREAD

**Issue by manndave** [OfficeDev/office-ui-fabric-js#262]
Are there typings files for the components somewhere that I'm not finding?  Trying to use components in Angular2 and nothing to import to get me 'fabric'

Thanks.

**Comment by Jahnp** [comment]
There aren't today, but we're tracking votes for this [on the Trello board](https://trello.com/c/S7rgV8Ip/28-typescript-definitions-for-components). I think we'd all like to see these, but are gauging interest before committing to a timeline/priority for them. 

Since this is on the Trello board and this was raised in #101, if you don't mind, I'll go ahead and close this issue for now.

**Comment by manndave** [comment]
Thanks.  Voted on Trello board.  :-)
