### ISSUE TITLE
ChoiceFieldGroup - need function to return value

### ISSUE THREAD

**Issue by Reezaali** [OfficeDev/office-ui-fabric-js#309]
It would be a nice addition to have a function to call on a choicefieldgroup that would return the value of the selected radio button. Thanks!

**Comment by Danny-Engelman** [comment]
They emit a custom event: ``msChoiceField``

So all you have to do is:

```typescript
    document.addEventListener("msChoicefield", function (event) {
          let radioClicked = <HTMLInputElement>event.srcElement;


    }, false);
```

**Comment by WrathOfZombies** [comment]
There are a couple of problems to this:

1. What if there were multiple choice field groups on the page? How would you classify them based on the event alone? One can definitely work around the problem but I feel that it should be handled as a part of the initialization code itself.

Example: 
````typescript
  var choiceFieldGroup = new fabric.ChoiceFieldGroup($('.ms-ChoiceFieldGroup')[0]);

 /* assuming you had an onSelectionChanged method on a ChoiceFieldGroup */
  choiceFieldGroup.onSelectionChanged((radio:RadioButton) => {
         /* Do something with the radio button in that group */
  });
````

2. In the current implementation to get the attributes of the radio button you would need to do something like:
````typescript
$(document).on('msChoicefield', (event) => {
    let radioButton = $(event.target).parent('.ms-RadioButton');
    console.log(radioButton.data('color'))
});
````
In which case I am recreating the RadioButton over and over again instead of just caching it or getting it from the ChoiceFieldGroup object itself. I see that the ChoiceFieldGroup object has private members where it stores the radio buttons.

**Comment by Danny-Engelman** [comment]
Sorry, I unlearned jQuery some time ago.
Why is jQuery recreating the RadioButton and not just returning a pointer to a DOM element?

**Comment by FelipeCostaGualberto** [comment]
A function that would look up for its `_choiceFieldComponents` that matches the same `name` attribute would be great!

**Comment by Linda-Editor** [comment]
Microsoft no longer supports this content and will not be responding to bugs or issues. We recommend that you use the newer version, [Office UI Fabric](https://developer.microsoft.com/fabric), with React as your front-end framework. We are closing this issue; if you still need assistance with Fabric.js, visit [Stack Overflow/office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).
