### ISSUE TITLE
Datepicker in sharepoint framework?

### ISSUE THREAD

**Issue by BhargavJanardhan** [OfficeDev/office-ui-fabric-js#318]
Hello folks,

I am trying to add datepicker in SharePoint framework, but I didn't find any correct solution yet.
Is there any way we can add it?

Thanks in Advance,
Bhargav

**Comment by BhargavJanardhan** [comment]
Hello Folks,

Now I am able to add date picker using fabric-js in SharePoint framework.
Below is the approach I followed.
https://dev.office.com/fabric#/components/datepicker

![capture](https://cloud.githubusercontent.com/assets/27334482/24959012/fcbb61fc-1fae-11e7-96d9-6f4323c1e15a.PNG)

But how can I use timepicker with the date?

Thanks,
Bhargav

**Comment by Jahnp** [comment]
Hey @BhargavJanardhan, sorry for the delay! Just checking, is this issue directed at Fabric JS (this repo) or [Fabric React](https://github.com/OfficeDev/office-ui-fabric-react/)? The DatePicker in your screenshot looks like the React one. If that's the case, would you mind re-opening this issue in that repo? We currently don't have a TimePicker component, but it's possible that one of the teams using Fabric React will have a similar need, so you'd likely get more traction on this issue there. 

Because it looks like this issue is directed at Fabric React, I'll go ahead and close this for now, but please feel free to open it back up if I got that wrong.
